### ISSUE TITLE
Did you ever get it working?

### ISSUE THREAD

**Issue by kavink** [d0ugal/mistral-on-heroku#1]
Wondering if you ever were able to successfully deploy to Heroku?

**Comment by d0ugal** [comment]
No, I didn’t get it fully working. I was close but I never found time to figure it all out.

**Comment by kavink** [comment]
@d0ugal Thanks, just curious Did you never use mistral or you moved to another workflow framework ?

**Comment by d0ugal** [comment]
Yes, I use Mistral - but I am also one of the Mistral developers :)
